gives me Error on all exceptions check do i need to create an instance of Exceptions in matrix ??
use define ot const string for errors for exception

error: 'OUT_OF_BOUNDARIES' was not declared in this s
cope
   throw Exceptions(OUT_OF_BOUNDARIES);
                    ^